-- RealCatch.io Database Schema

-- Properties scraped from Volusia County Property Appraiser
CREATE TABLE IF NOT EXISTS properties (
  id SERIAL PRIMARY KEY,
  parcel_id VARCHAR(30) UNIQUE NOT NULL,
  owner_name VARCHAR(255),
  owner_address VARCHAR(500),
  owner_city VARCHAR(100),
  owner_state VARCHAR(2),
  owner_zip VARCHAR(10),
  property_address VARCHAR(500),
  property_city VARCHAR(100),
  property_zip VARCHAR(10),
  property_type VARCHAR(50),
  assessed_value BIGINT,
  market_value BIGINT,
  taxable_value BIGINT,
  last_sale_date DATE,
  last_sale_price BIGINT,
  homestead BOOLEAN DEFAULT FALSE,
  tax_delinquent BOOLEAN DEFAULT FALSE,
  tax_delinquent_amount NUMERIC(12,2),
  tax_delinquent_years INTEGER DEFAULT 0,
  legal_description TEXT,
  acreage NUMERIC(10,4),
  year_built INTEGER,
  bedrooms INTEGER,
  bathrooms NUMERIC(4,1),
  sqft INTEGER,
  raw_data JSONB,
  first_seen_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_properties_zip ON properties(property_zip);
CREATE INDEX idx_properties_owner_state ON properties(owner_state);
CREATE INDEX idx_properties_tax_delinquent ON properties(tax_delinquent);
CREATE INDEX idx_properties_last_sale ON properties(last_sale_date);
CREATE INDEX idx_properties_updated ON properties(updated_at);

-- LLC filings from FL Sunbiz
CREATE TABLE IF NOT EXISTS llc_filings (
  id SERIAL PRIMARY KEY,
  document_number VARCHAR(30) UNIQUE NOT NULL,
  entity_name VARCHAR(500) NOT NULL,
  filing_date DATE,
  status VARCHAR(50),
  principal_name VARCHAR(255),
  principal_address VARCHAR(500),
  principal_city VARCHAR(100),
  principal_state VARCHAR(2),
  principal_zip VARCHAR(10),
  registered_agent VARCHAR(255),
  category VARCHAR(100),
  raw_data JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_llc_filing_date ON llc_filings(filing_date);
CREATE INDEX idx_llc_category ON llc_filings(category);

-- Foreclosure auctions from realforeclose.com
CREATE TABLE IF NOT EXISTS foreclosures (
  id SERIAL PRIMARY KEY,
  case_number VARCHAR(50) UNIQUE NOT NULL,
  property_address VARCHAR(500),
  city VARCHAR(100),
  zip VARCHAR(10),
  defendant_name VARCHAR(255),
  plaintiff_name VARCHAR(255),
  auction_date DATE,
  opening_bid NUMERIC(12,2),
  assessed_value BIGINT,
  status VARCHAR(50) DEFAULT 'scheduled',
  parcel_id VARCHAR(30),
  raw_data JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_foreclosure_auction ON foreclosures(auction_date);
CREATE INDEX idx_foreclosure_zip ON foreclosures(zip);
CREATE INDEX idx_foreclosure_parcel ON foreclosures(parcel_id);

-- Scored leads generated by the AI engine
CREATE TABLE IF NOT EXISTS leads (
  id SERIAL PRIMARY KEY,
  parcel_id VARCHAR(30) NOT NULL REFERENCES properties(parcel_id),
  score INTEGER NOT NULL CHECK (score >= 0 AND score <= 100),
  signals JSONB NOT NULL DEFAULT '[]',
  ai_summary TEXT,
  lead_type VARCHAR(50),
  status VARCHAR(20) DEFAULT 'new',
  scored_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_leads_score ON leads(score DESC);
CREATE INDEX idx_leads_scored_at ON leads(scored_at);
CREATE INDEX idx_leads_type ON leads(lead_type);

-- Subscribers (paying customers)
CREATE TABLE IF NOT EXISTS subscribers (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255),
  salt VARCHAR(64),
  name VARCHAR(255),
  company VARCHAR(255),
  phone VARCHAR(20),
  tier VARCHAR(20) NOT NULL DEFAULT 'free',
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  stripe_customer_id VARCHAR(100),
  stripe_subscription_id VARCHAR(100),
  zip_codes TEXT[] DEFAULT '{}',
  min_score INTEGER DEFAULT 60,
  digest_frequency VARCHAR(10) DEFAULT 'weekly',
  last_digest_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_subscribers_email ON subscribers(email);
CREATE INDEX idx_subscribers_tier ON subscribers(tier);
CREATE INDEX idx_subscribers_stripe ON subscribers(stripe_customer_id);

-- Prospects (potential customers found from public data)
CREATE TABLE IF NOT EXISTS prospects (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255),
  name VARCHAR(255),
  company VARCHAR(255),
  source VARCHAR(50) NOT NULL,
  source_id VARCHAR(100),
  prospect_type VARCHAR(50),
  notes TEXT,
  status VARCHAR(20) DEFAULT 'new',
  last_contacted TIMESTAMPTZ,
  converted BOOLEAN DEFAULT FALSE,
  subscriber_id INTEGER REFERENCES subscribers(id),
  raw_data JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_prospects_status ON prospects(status);
CREATE INDEX idx_prospects_source ON prospects(source);

-- Email log for tracking
CREATE TABLE IF NOT EXISTS email_log (
  id SERIAL PRIMARY KEY,
  subscriber_id INTEGER REFERENCES subscribers(id),
  recipient_email VARCHAR(255) NOT NULL,
  email_type VARCHAR(50) NOT NULL,
  subject VARCHAR(500),
  mailgun_id VARCHAR(100),
  status VARCHAR(20) DEFAULT 'sent',
  opened_at TIMESTAMPTZ,
  clicked_at TIMESTAMPTZ,
  sent_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_email_recipient ON email_log(recipient_email);
CREATE INDEX idx_email_type ON email_log(email_type);

-- Ownership change tracking
CREATE TABLE IF NOT EXISTS ownership_changes (
  id SERIAL PRIMARY KEY,
  parcel_id VARCHAR(30) NOT NULL,
  old_owner VARCHAR(255),
  new_owner VARCHAR(255),
  sale_date DATE,
  sale_price BIGINT,
  detected_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_ownership_parcel ON ownership_changes(parcel_id);
CREATE INDEX idx_ownership_date ON ownership_changes(detected_at);
